---
- name: Remove existing files TO REMOVE
  file:
    path: "{{ whanos_root }}"
    state: absent
  notify: Restart Jenkins

- name: Remove existing files TO REMOVE
  file:
    path: "{{ jenkins_home }}"
    state: absent
  notify: Restart Jenkins

- name: Add Jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '0755'

- name: Download Jenkins plugin manager
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.11/jenkins-plugin-manager-2.12.11.jar
    dest: /usr/local/bin/jenkins-plugin-manager.jar
    mode: '0755'

- name: Install required packages
  apt:
    name:
      - jenkins
      - openjdk-17-jdk
      - gettext-base  # for envsubst
    state: present
    update_cache: yes

- name: Create Jenkins directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'
  with_items:
    - "{{ jenkins_home }}"
    - "{{ jenkins_home }}/kube"
    - "{{ jenkins_home }}/plugins"
    - "{{ whanos_root }}"
    - "{{ whanos_root }}/jenkins"
    - "{{ whanos_root }}/images"

- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Ensure Jenkins home directory permissions
  file:
    path: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    recurse: yes
    mode: '0755'
    state: directory

- name: Copy Jenkins files
  copy:
    src: "{{ playbook_dir }}/../jenkins/"
    dest: "{{ whanos_root }}/jenkins/"
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy images
  copy:
    src: "{{ playbook_dir }}/../images/"
    dest: "{{ whanos_root }}/images/"
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy kubeconfig file
  copy:
    src: "{{ local_kubeconfig_path }}"
    dest: "{{ kubeconfig_path }}"
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Read plugins list
  slurp:
    src: "{{ whanos_root }}/jenkins/plugins.txt"
  register: plugins_content

- name: Check if plugins need to be installed
  stat:
    path: "{{ jenkins_home }}/plugins/{{ item | regex_replace(':.*$','') }}"
  register: jenkins_plugins_check
  with_items: "{{ plugins_content.content | b64decode | split('\n') }}"
  notify: Install Jenkins plugins
  changed_when: not jenkins_plugins_check.stat.exists
  when: item != ""

- name: Configure Jenkins service
  template:
    src: jenkins.service.j2
    dest: /lib/systemd/system/jenkins.service
    mode: '0644'
  notify: Restart Jenkins

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  notify: Restart Jenkins

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  notify: Restart Jenkins

- name: Create handlers directory
  file:
    path: "{{ role_path }}/handlers"
    state: directory
    mode: '0755'