FROM alpine:3.20

RUN apk add --no-cache bash gcc musl-dev make curl
SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

ARG BEFUNGE93_SHA=8fe4065c0415b6f6fa6f699798fa9b64737aadc1
RUN curl -fsSL "https://codeload.github.com/catseye/Befunge-93/tar.gz/${BEFUNGE93_SHA}" \
      | tar xz \
    && make -C "Befunge-93-${BEFUNGE93_SHA}" \
    && install -m 0755 "Befunge-93-${BEFUNGE93_SHA}/bin/bef" /usr/local/bin/bef \
    && rm -rf "/tmp/Befunge-93-${BEFUNGE93_SHA}" \
    && apk del gcc musl-dev make curl

WORKDIR /app

COPY . .
RUN test -f ./app/main.bf \
    && rm -rf Dockerfile* .git*

CMD ["/usr/local/bin/bef", "./app/main.bf"]
