FROM gcc:13

SHELL ["/bin/bash", "-c"]

WORKDIR /app

ONBUILD COPY Makefile .
ONBUILD COPY . .
ONBUILD RUN make && \
    mv compiled-app /compiled-app && \
    rm -rf /app/* && \
    rm -rf Dockerfile* .git*

ONBUILD CMD ["/compiled-app"]
