# VPS Configuration
vps_ip: ""
vps_root_password: ""

# Jenkins Configuration
jenkins_admin_password: "change_me"
jenkins_url: "http://{{ vps_ip }}"

# Paths
jenkins_home: "/var/lib/jenkins"
whanos_root: "/opt/whanos"

# DigitalOcean Container Registry
# Required for pushing images to DigitalOcean Container Registry
registry_username: "" # Your DigitalOcean email
registry_token: ""    # Your DigitalOcean API token with registry access
