terraform {
  required_version = ">= 1.5.0"

  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.34"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }

  # Optional: configure a remote backend (DO Spaces / S3) before team use.
  # backend "s3" { ... }
}

provider "digitalocean" {
  # Uses DIGITALOCEAN_TOKEN / DIGITALOCEAN_ACCESS_TOKEN from the environment.
}

variable "project_name" {
  type    = string
  default = "whanos-dev"
}

variable "region" {
  type    = string
  default = "fra1"
}

variable "registry_name" {
  type    = string
  default = "whanos"
}

variable "cluster_node_count" {
  type    = number
  default = 1
}

variable "cluster_node_size" {
  type    = string
  default = "s-2vcpu-2gb"
}

variable "jenkins_droplet_size" {
  type    = string
  default = "s-2vcpu-2gb"
}

variable "ssh_public_key_path" {
  type    = string
  default = "../../../ansible/ssh/whanos_vps.pub"
}

variable "ssh_allow_cidrs" {
  type    = list(string)
  default = ["0.0.0.0/0"]
}

variable "enable_https" {
  type    = bool
  default = false
}

locals {
  repo_root = abspath("${path.module}/../../..")
}

module "registry" {
  source            = "../../modules/registry"
  name              = var.registry_name
  region            = var.region
  subscription_tier = "starter"
}

module "cluster" {
  source          = "../../modules/cluster"
  name            = "${var.project_name}-k8s"
  region          = var.region
  node_count      = var.cluster_node_count
  node_size       = var.cluster_node_size
  kubeconfig_path = "${local.repo_root}/kubeconfig.yaml"
}

module "jenkins_vps" {
  source                = "../../modules/jenkins-vps"
  name                  = "${var.project_name}-jenkins"
  region                = var.region
  size                  = var.jenkins_droplet_size
  ssh_public_key_path   = var.ssh_public_key_path
  ssh_allow_cidrs       = var.ssh_allow_cidrs
  enable_https          = var.enable_https
  ansible_inventory_path = "${local.repo_root}/ansible/inventory.tf.yml"
}

resource "local_file" "ansible_tf_vars" {
  filename = "${local.repo_root}/ansible/group_vars/tf.generated.yml"
  content  = <<-EOT
    # Generated by Terraform (dev) — copy values into all.yml or include this file.
    # Do not commit secrets; this file is gitignored.
    vps_ip: "${module.jenkins_vps.ipv4_address}"
    jenkins_url: "http://${module.jenkins_vps.ipv4_address}"
    registry_host: "registry.digitalocean.com"
    registry_name: "${module.registry.name}"
    local_kubeconfig_path: "{{ playbook_dir }}/../kubeconfig.yaml"
    kubeconfig_path: "{{ jenkins_home }}/kube/config"
  EOT
  file_permission = "0644"
}

output "registry_endpoint" {
  value = module.registry.endpoint
}

output "jenkins_ipv4" {
  value = module.jenkins_vps.ipv4_address
}

output "kubeconfig_path" {
  value = module.cluster.kubeconfig_path
}

output "cluster_id" {
  value = module.cluster.id
}

output "next_steps" {
  value = <<-EOT
    1) doctl registry kubernetes-integration create --cluster-uuid ${module.cluster.id}
    2) Merge ansible/group_vars/tf.generated.yml into all.yml (add passwords/tokens)
    3) make run-ansible
    4) Open http://${module.jenkins_vps.ipv4_address}/
  EOT
}
