terraform {
  required_version = ">= 1.5.0"
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.34"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

variable "name" {
  type = string
}

variable "region" {
  type    = string
  default = "fra1"
}

variable "size" {
  type        = string
  description = "Droplet size. Prod should be at least s-2vcpu-2gb (not 512MB)."
  default     = "s-2vcpu-2gb"
}

variable "image" {
  type    = string
  default = "debian-12-x64"
}

variable "ssh_public_key_path" {
  type        = string
  description = "Path to the public key installed on the droplet (e.g. ansible/ssh/whanos_vps.pub)."
}

variable "ssh_allow_cidrs" {
  type        = list(string)
  description = "CIDRs allowed to SSH (prod: your IP/32). Dev may use 0.0.0.0/0."
  default     = ["0.0.0.0/0"]
}

variable "enable_https" {
  type        = bool
  default     = false
  description = "Open TCP/443 on the cloud firewall (TLS terminated by nginx/Ansible)."
}

variable "tags" {
  type    = list(string)
  default = ["whanos", "jenkins"]
}

variable "ansible_inventory_path" {
  type        = string
  description = "Generated inventory snippet for Ansible (gitignored)."
  default     = ""
}

resource "digitalocean_ssh_key" "this" {
  name       = "${var.name}-ansible"
  public_key = file(var.ssh_public_key_path)
}

resource "digitalocean_droplet" "this" {
  name       = var.name
  region     = var.region
  size       = var.size
  image      = var.image
  ssh_keys   = [digitalocean_ssh_key.this.id]
  tags       = var.tags
  monitoring = true
}

resource "digitalocean_firewall" "this" {
  name = "${var.name}-fw"

  droplet_ids = [digitalocean_droplet.this.id]

  inbound_rule {
    protocol         = "tcp"
    port_range       = "22"
    source_addresses = var.ssh_allow_cidrs
  }

  inbound_rule {
    protocol         = "tcp"
    port_range       = "80"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }

  dynamic "inbound_rule" {
    for_each = var.enable_https ? [1] : []
    content {
      protocol         = "tcp"
      port_range       = "443"
      source_addresses = ["0.0.0.0/0", "::/0"]
    }
  }

  outbound_rule {
    protocol              = "tcp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }

  outbound_rule {
    protocol              = "udp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }

  outbound_rule {
    protocol              = "icmp"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
}

resource "local_file" "ansible_inventory" {
  count = var.ansible_inventory_path != "" ? 1 : 0

  filename = var.ansible_inventory_path
  content  = <<-EOT
    # Generated by Terraform — do not commit.
    # Merge with ansible/inventory.yml or set vps_ip in group_vars.
    all:
      hosts:
        whanos:
          ansible_host: "${digitalocean_droplet.this.ipv4_address}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ inventory_dir }}/ssh/whanos_vps"
          ansible_become: true
  EOT
  file_permission = "0644"
}

output "ipv4_address" {
  value = digitalocean_droplet.this.ipv4_address
}

output "droplet_id" {
  value = digitalocean_droplet.this.id
}

output "ssh_key_fingerprint" {
  value = digitalocean_ssh_key.this.fingerprint
}
