---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx for Jenkins
  template:
    src: jenkins.nginx.conf.j2
    dest: /etc/nginx/sites-available/jenkins
    mode: '0644'
  notify: reload nginx

- name: Enable Jenkins site
  file:
    src: /etc/nginx/sites-available/jenkins
    dest: /etc/nginx/sites-enabled/jenkins
    state: link
  notify: reload nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes