jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - entries:
          - user: "admin"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        name: "Admin"
        password: "${JENKINS_ADMIN_PASSWORD}"
  projectNamingStrategy:
    roleBased:
      forceExistingJobs: true
  noUsageStatistics: true
  remotingSecurity:
    enabled: true
  systemMessage: "Welcome to the Whanos instance."
  views:
  - all:
      name: "all"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  location:
    adminAddress: "contact@email.fr"
    url: "${JENKINS_URL:-http://localhost:8080}"
  scmGit:
    globalConfigName: "${GIT_USERNAME:-Whanos}"
    globalConfigEmail: "${GIT_EMAIL:-whanos@jenkins.local}"

jobs:
  - file: /jenkins/jobs/folders.groovy
  - file: /jenkins/jobs/base_images_jobs.groovy
  - file: /jenkins/jobs/link_project.groovy
