jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - entries:
          - user: "admin"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        name: "Admin"
        password: "${JENKINS_ADMIN_PASSWORD}"
  projectNamingStrategy:
    roleBased:
      forceExistingJobs: true
  noUsageStatistics: true
  remotingSecurity:
    enabled: true
  systemMessage: "Welcome to the Whanos instance."

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"

unclassified:
  location:
    adminAddress: "contact@email.fr"
    url: "${JENKINS_URL:-http://localhost:8080}"

jobs:
  - file: /opt/whanos/jenkins/jobs/folders.groovy
  - file: /opt/whanos/jenkins/jobs/base_images_jobs.groovy
  - file: /opt/whanos/jenkins/jobs/link_project.groovy

credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          id: "do-registry-token"
          secret: "${REGISTRY_TOKEN}"
          description: "DigitalOcean Registry Token"
          scope: GLOBAL
      - string:
          id: "do-registry-username"
          secret: "${REGISTRY_USERNAME}"
          description: "DigitalOcean Registry Username"
          scope: GLOBAL
      - file:
          id: "kubernetes-config"
          description: "Kubernetes config file"
          fileName: "config"
          secretBytes: "${KUBECONFIG_CONTENT}"
          scope: GLOBAL
