terraform {
  required_version = ">= 1.5.0"

  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.34"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "digitalocean" {}

variable "project_name" {
  type    = string
  default = "whanos-prod"
}

variable "region" {
  type    = string
  default = "fra1"
}

variable "registry_name" {
  type    = string
  default = "whanos"
}

variable "cluster_node_count" {
  type    = number
  default = 2

  validation {
    condition     = var.cluster_node_count >= 2
    error_message = "Production DOKS must have at least 2 nodes (Whanos subject)."
  }
}

variable "cluster_node_size" {
  type    = string
  default = "s-2vcpu-4gb"
}

variable "jenkins_droplet_size" {
  type        = string
  default     = "s-2vcpu-4gb"
  description = "Avoid 512MB droplets — Jenkins needs RAM + disk for builds."
}

variable "ssh_public_key_path" {
  type    = string
  default = "../../../ansible/ssh/whanos_vps.pub"
}

variable "ssh_allow_cidrs" {
  type        = list(string)
  description = "Restrict SSH to your admin IP(s), e.g. [\"203.0.113.10/32\"]."
}

variable "enable_https" {
  type    = bool
  default = true
}

locals {
  repo_root = abspath("${path.module}/../../..")
}

module "registry" {
  source            = "../../modules/registry"
  name              = var.registry_name
  region            = var.region
  subscription_tier = "starter"
}

module "cluster" {
  source          = "../../modules/cluster"
  name            = "${var.project_name}-k8s"
  region          = var.region
  node_count      = var.cluster_node_count
  node_size       = var.cluster_node_size
  ha              = false # set true for HA control plane (slower + ~$40/mo)
  kubeconfig_path = "${local.repo_root}/kubeconfig.yaml"
}

module "jenkins_vps" {
  source                 = "../../modules/jenkins-vps"
  name                   = "${var.project_name}-jenkins"
  region                 = var.region
  size                   = var.jenkins_droplet_size
  ssh_public_key_path    = var.ssh_public_key_path
  ssh_allow_cidrs        = var.ssh_allow_cidrs
  enable_https           = var.enable_https
  ansible_inventory_path = "${local.repo_root}/ansible/inventory.tf.yml"
}

# Ansible loads host_vars/whanos.yml automatically (overrides stale group_vars/all.yml).
locals {
  ansible_tf_vars = <<-EOT
    # Generated by Terraform (prod) — do not commit. Secrets stay in repo-root .env.
    vps_ip: "${module.jenkins_vps.ipv4_address}"
    jenkins_url: "https://${module.jenkins_vps.ipv4_address}"
    registry_host: "registry.digitalocean.com"
    registry_name: "${module.registry.name}"
    local_kubeconfig_path: "{{ playbook_dir }}/../kubeconfig.yaml"
    kubeconfig_path: "{{ jenkins_home }}/kube/config"
  EOT
}

resource "local_file" "ansible_host_vars" {
  filename        = "${local.repo_root}/ansible/host_vars/whanos.yml"
  content         = local.ansible_tf_vars
  file_permission = "0644"
}

resource "local_file" "ansible_tf_vars" {
  filename        = "${local.repo_root}/ansible/group_vars/tf.generated.yml"
  content         = local.ansible_tf_vars
  file_permission = "0644"
}

output "registry_endpoint" {
  value = module.registry.endpoint
}

output "jenkins_ipv4" {
  value = module.jenkins_vps.ipv4_address
}

output "kubeconfig_path" {
  value = module.cluster.kubeconfig_path
}

output "cluster_id" {
  value = module.cluster.id
}

output "next_steps" {
  value = <<-EOT
    1) doctl kubernetes cluster registry add ${module.cluster.id}
    2) make run-ansible
       (Terraform wrote ansible/host_vars/whanos.yml; secrets in .env; optional ACME TLS)
    3) Open https://${module.jenkins_vps.ipv4_address}/ (or http if TLS not enabled yet)
  EOT
}
