FROM node:20-alpine

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]

WORKDIR /app

ONBUILD COPY package*.json ./
ONBUILD RUN npm install --production && rm package*.json

ONBUILD COPY . .
ONBUILD RUN rm -rf Dockerfile* .git*

ONBUILD CMD ["node", "."]